import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../public/assets/styles/ticket.css";
import "../public/assets/styles/style-new.css";
import Header from "./components/common/headers/Header";
import Providers from "./providers";
import Footer from "./components/common/footers/Footer";

import Loader from "./components/common/loader/Loader";
import { VISITOR_ACCESS_COOKIE } from "./lib/auth-cookies";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const isAuthenticated = cookieStore.has(VISITOR_ACCESS_COOKIE);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      data-scroll-behavior="smooth"
    >
      <body>
        <Providers>
          <Loader />
          <Header isAuthenticated={isAuthenticated} />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
