import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../public/assets/styles/ticket.css";
import "../public/assets/styles/style-new.css";
import Header from "./components/common/headers/Header";
import AuthenticatedHeader from "./components/common/headers/AuthenticatedHeader";
import UtmCapture from "./components/analytics/UtmCapture";
import Providers from "./providers";
import Footer from "./components/common/footers/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      data-scroll-behavior="smooth"
    >
      <body>
        <Providers>
          <UtmCapture />
          <Suspense fallback={<Header isAuthenticated={false} />}>
            <AuthenticatedHeader />
          </Suspense>
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
